### ISSUE TITLE
Use babel-preset-vue-app

### ISSUE THREAD

**Issue by egoist** [eddyerburgh/jest-vue#10]
use https://github.com/vuejs/babel-preset-vue-app as the default babel options

https://github.com/eddyerburgh/jest-vue/blob/88a230a230d0ec4c72f37080a4072e365a4bb812/lib/compilers/babel-compiler.js#L6-L9

**Comment by egoist** [comment]
Basically I want to make https://github.com/egoist/test-vue-app work out of the box without a `.babelrc` file, it would also be great if we can supply custom transformer options like in babel-jest: https://github.com/egoist/test-vue-app/blob/master/lib/jest/babel-transform.js

**Comment by eddyerburgh** [comment]
Thanks for the suggestion @egoist.

I added this in 0.8.0 🙂
