### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by stephane** [eddyerburgh/jest-vue#11]
It's not an issue!
Could you express your opinion about https://github.com/vire/jest-vue-preprocessor?
A small list of pros/cons against jest-vue-preprocessor in the README of jest-vue would be certainly useful to me and others.

**Comment by eddyerburgh** [comment]
I originally wrote this because jest-vue-preprocessor didn't support source maps, but it looks like it does now.

The one difference I can see is that we use `babel-preset-vue-app` instead of `babel-preset-env`
