### ISSUE TITLE
Why does Vue core recommend using this instead of jest-vue-preprocessor?

### ISSUE THREAD

**Issue by flybayer** [eddyerburgh/jest-vue#15]
Hello,

I'm working on integrating `vue-test-utils` into my existing project which uses `jest` and [`jest-vue-preprocessor`](https://github.com/vire/jest-vue-preprocessor).

The `vue-test-utils` docs say to use this `jest-vue` package, but I don't understand why I would use one over the other. I'm sure there are significant differences I don't understand.

I'd appreciate any help you can give!

Thanks!

**Comment by eddyerburgh** [comment]
When the docs were written, jest-vue supported source maps and vue-jest didn't. Now they both support source maps, so there isn't a huge difference.
