### ISSUE TITLE
babel-compiler.js always uses jest-vue's .babelrc

### ISSUE THREAD

**Issue by mjkillough** [eddyerburgh/jest-vue#2]
`babel-compiler.js` is currently [passing its own `lib/` directory to `find-babel-config`](https://github.com/eddyerburgh/jest-vue/blob/cd66ba01eba17765b115e88e5674c809acbeea74/lib/compilers/babel-compiler.js#L16), which means it always compiles code using jest-vue's `.babelrc` and not the project's.

The comments suggest that it should instead be passing the current working directory. I think it would be even better if `process.js` passed the `path` of the script being compiled to be used.

**Comment by eddyerburgh** [comment]
This should be fixed in 0.5.1

Can you confirm the fix?

**Comment by mjkillough** [comment]
That works, thanks!
