### ISSUE TITLE
Issues in branches coverage

### ISSUE THREAD

**Issue by vanessasml** [eddyerburgh/jest-vue#3]
I’ve added [jest-vue](https://github.com/eddyerburgh/jest-vue) to my project and I realized that the values for the branches coverage are incorrect. I tried the same with your project [vue-test-utils-jest-example-master](https://github.com/eddyerburgh/vue-test-utils-jest-example) and the issues are the same. 
￼
![screen shot 2017-09-07 at 12 28 24](https://user-images.githubusercontent.com/17016650/30161860-44b3a750-93ca-11e7-8455-67a00bd17f74.png)

You can notice that the template lines are included in the coverage calculation and it also shows 50% of 6 branches coverage when you don’t even have a single branch in the file… Something is wrong here. Can you look at it?

**Comment by eddyerburgh** [comment]
Have you added `"mapCoverage": true` to your Jest config?

Like this - https://github.com/eddyerburgh/jest-vue/blob/master/package.json#L71

**Comment by vanessasml** [comment]
Yes, I added it to your project, and It's still not working. It seems that the rest of the coverage in statements, functions and lines are ok.

**Comment by eddyerburgh** [comment]
Ok, I see what you mean.

I'm not going to have time to look into this closely for a while. Maybe not until October 😕

Once I have a free weekend I'll investigate this issue properly and attempt to solve.
