### ISSUE TITLE
Render functions

### ISSUE THREAD

**Issue by marcosmoura** [eddyerburgh/jest-vue#6]
When using raw render functions instead of a `<template>` tag, it'll throw a error:
![screen shot 2017-09-14 at 23 53 05](https://user-images.githubusercontent.com/1357885/30464436-e1059478-99a7-11e7-86bf-eed337b709ac.png)

I will try to submit a PR ASAP...

**Comment by eddyerburgh** [comment]
Any luck with the PR?

**Comment by marcosmoura** [comment]
Yes! I manage to fix the issue by ignoring the undefined template part.

**Comment by eddyerburgh** [comment]
fixed by https://github.com/eddyerburgh/jest-vue/pull/7

**Comment by eddyerburgh** [comment]
thanks for the PR, I've released in version 0.5.4
