### ISSUE TITLE
Switch to babel-preset-env

### ISSUE THREAD

**Issue by ankurk91** [eddyerburgh/jest-vue#9]
Hi,
I got this warning when installing `jest-vue`
![screenshot from 2017-10-02 12-49-32](https://user-images.githubusercontent.com/6111524/31067502-cc96c24c-a770-11e7-803e-8d36de9f3265.png)

You are already `babel-preset-env` as devDependency
https://github.com/eddyerburgh/jest-vue/blob/f4b55cc60b4795c6ed3215b79cf49d9b928d4945/package.json#L31

But end user is forced to install `babel-preset-es2015`
https://github.com/eddyerburgh/jest-vue/blob/f4b55cc60b4795c6ed3215b79cf49d9b928d4945/package.json#L54

Is there any reason behind this ?

Thanks.

**Comment by eddyerburgh** [comment]
Hi, thanks for the issue.

I've replaced babel preset es2015 with babel-preset-env in 0.7.0. Can you give it a go?

**Comment by ankurk91** [comment]
Worked, thanks.

**Comment by egoist** [comment]
Hmm can we switch to https://github.com/vuejs/babel-preset-vue-app?
